name: deploy

on:
  workflow_dispatch:

jobs:
  image:
    name: push image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: setup tinygo
        uses: rajatjindal/setup-actions/tinygo@b4a3ac9f32a080efff631ecd0b9a408830a6fb79 # v.0.0.1
        with:
          version: v0.28.1

      - name: setup spin
        uses: fermyon/actions/spin/setup@7f8c6c3006d78c2465aab9f3c3f4727d32fea836 # v1.0.5

        # need to lowercase repository because ghcr requires reference in lowercase
      - name: get repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
        id: repo

      - name: spin push
        uses: fermyon/actions/spin/push@7f8c6c3006d78c2465aab9f3c3f4727d32fea836 # v1.0.5
        with: 
          registry: ghcr.io 
          registry_username: ${{ github.actor }} 
          registry_password: ${{ secrets.GITHUB_TOKEN }} 
          registry_reference: "ghcr.io/${{ steps.repo.outputs.REPO }}:${{ github.sha }}"




